"""users table

Revision ID: 3678e4d0b2ab
Revises: d0a57670911a
Create Date: 2019-08-11 14:25:44.351929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3678e4d0b2ab'
down_revision = 'd0a57670911a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_terminal_ip', table_name='terminal')
    op.create_index(op.f('ix_terminal_ip'), 'terminal', ['ip'], unique=True)
    op.drop_index('ix_terminal_mac', table_name='terminal')
    op.create_index(op.f('ix_terminal_mac'), 'terminal', ['mac'], unique=True)
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('telephone_number', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_telephone_number'), 'user', ['telephone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telephone_number'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'telephone_number')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_terminal_mac'), table_name='terminal')
    op.create_index('ix_terminal_mac', 'terminal', ['mac'], unique=False)
    op.drop_index(op.f('ix_terminal_ip'), table_name='terminal')
    op.create_index('ix_terminal_ip', 'terminal', ['ip'], unique=False)
    # ### end Alembic commands ###
