"""users table

Revision ID: d0a57670911a
Revises: 
Create Date: 2019-08-11 12:35:23.293864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a57670911a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_name', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('pricing_method', sa.Enum('weight', 'quantity'), nullable=True),
    sa.Column('about', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodity_commodity_name'), 'commodity', ['commodity_name'], unique=False)
    op.create_table('terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('mac', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_ip'), 'terminal', ['ip'], unique=False)
    op.create_index(op.f('ix_terminal_mac'), 'terminal', ['mac'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('weixin_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_index(op.f('ix_user_weixin_id'), 'user', ['weixin_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Enum('unpaid', 'paid'), nullable=True),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_timestamp'), 'order', ['timestamp'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Float(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_order_timestamp'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_weixin_id'), table_name='user')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_terminal_mac'), table_name='terminal')
    op.drop_index(op.f('ix_terminal_ip'), table_name='terminal')
    op.drop_table('terminal')
    op.drop_index(op.f('ix_commodity_commodity_name'), table_name='commodity')
    op.drop_table('commodity')
    # ### end Alembic commands ###
